apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer.carto.run.0.2.1
  annotations:
    kapp.k14s.io/change-group: carto.run/install
    kapp.k14s.io/change-rule: upsert after upserting carto.run/meta
spec:
  serviceAccountName: default
  packageRef:
    refName: cartographer.carto.run
    versionSelection:
      constraints: 0.2.1
