---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: meta-package.community.tanzu.vmware.com.0.1.0
spec:
  refName: meta-package.community.tanzu.vmware.com
  version: 0.1.0
  releasedAt: 2022-02-01T14:53:24Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: "dev.registry.tanzu.vmware.com/tap-gui/meta-package-bundle:0.1.0"
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        contour:
          type: object
          default: {}
          description: "contour values"
