apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer.carto.run.0.2.1
  annotations:
    kapp.k14s.io/change-group: carto.run/meta
spec:
  refName: cartographer.carto.run
  version: 0.2.1
  releaseNotes: https://github.com/vmware-tanzu/cartographer/releases/tag/0.2.1
  releasedAt: "2022-01-24T16:10:07Z"
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: index.docker.io/projectcartographer/cartographer-bundle@sha256:d2c94525e9ab44ee50b5a0e187dc7006a6d7229872f7fd16e6dc07b2b3603ed7
      template:
      - ytt:
          ignoreUnknownComments: true
          inline:
            paths:
              namespace.yaml: |-
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: cartographer-system
      - kbld: {}
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
