---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-platform-install-cluster-admin-role
  annotations:
    kapp.k14s.io/change-group: serviceaccount
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-platform-install-cluster-admin-role-binding
  annotations:
    kapp.k14s.io/change-group: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-platform-install-cluster-admin-role
subjects:
  - kind: ServiceAccount
    name: app-platform-install-sa
    namespace: app-platform-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-platform-install-sa
  namespace: app-platform-install
  annotations:
    kapp.k14s.io/change-group: serviceaccount
