apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: secretgen-controller.community.tanzu.vmware.com.0.8.0
spec:
  refName: secretgen-controller.community.tanzu.vmware.com
  version: 0.8.0
  releaseNotes: secretgen-controller 0.8.0 https://github.com/vmware-tanzu/carvel-secretgen-controller
  licenses:
  - Apache 2.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tce/secretgen-controller@sha256:ef25443ee64e80e94132148d8e62eec5ba810b295638df2e9883933ad77525d9
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      description: OpenAPIv3 Schema for secretgen-controller
      properties:
        nodeSelector:
          nullable: true
          description: NodeSelector configuration applied to all the deployments
          default: null
        deployment:
          type: object
          additionalProperties: false
          properties:
            updateStrategy:
              type: string
              nullable: true
              description: Update strategy of deployments
              default: null
            rollingUpdate:
              type: object
              additionalProperties: false
              properties:
                maxUnavailable:
                  type: integer
                  nullable: true
                  description: The maxUnavailable of rollingUpdate. Applied only if rollingUpdate is used as updateStrategy
                  default: null
                maxSurge:
                  type: integer
                  nullable: true
                  description: The maxSurge of rollingUpdate. Applied only if rollingUpdate is used as updateStrategy
                  default: null
        daemonset:
          type: object
          additionalProperties: false
          properties:
            updateStrategy:
              type: string
              nullable: true
              description: Update strategy of daemonsets
              default: null
        secretgenController:
          type: object
          additionalProperties: false
          description: Configuration for secretgen-controller
          properties:
            namespace:
              type: string
              description: The namespace in which to deploy secretgen-controller
              default: secretgen-controller
            createNamespace:
              type: boolean
              description: Whether to create namespace specified for secretgen-controller
              default: true
